name: CFX Scheduled Daily Trivy Stable

on:
  schedule:
    # Once a day
    - cron: '0 0 * * *'
  workflow_dispatch:
  # Trigger manually
  pull_request:
    paths:
      - '.github/workflows/cfx_trivy_latest.yml'

concurrency:
  # cancel older running jobs on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-config:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # v0.32.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          output: 'config-trivy-results.sarif'
          vuln-type: 'os,library'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@4e828ff8d448a8a6e532957b1811f387a63867e8 # v3.29.4
        if: always()
        with:
          sarif_file: 'config-trivy-results.sarif'

  analyze-services:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    strategy:
      matrix:
        include:
          - service_name: frontend
    uses: Cofinity-X/central-pipelines/.github/workflows/reusable-trivy-acr-latest-image-scan.yaml@main
    name: Trivy Scan ${{ matrix.service_name }}
    with:
      environment: lower-env-acr
      image-name: ${{ matrix.service_name }}
      image-namespace: portal/portal-frontend/images
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
