name: CFX Lint PR Title

on:
  pull_request:
    branches: [main]

concurrency:
  # cancel older running jobs on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull_request_lint:
    permissions:
      pull-requests: write
    name: Lint PR Title
    uses: Cofinity-X/central-pipelines/.github/workflows/reusable-pull-request-lint.yaml@main
